### ISSUE TITLE
why should i use :std::: everytime?

### ISSUE THREAD

**Issue by mdsiaofficial** [rutura/The-C-20-Masterclass-Source-Code#10]
some other codes/other websites, I found they don't use "std::". instead, some of them said that "using namespace std" after header filer is replacing this "std::".
is this a good practice to use the "std::" every time?

**Comment by ankit27066** [comment]
i think no

**Comment by dluffy121** [comment]
It's about good practice, for a simple project like this where the purpose is to just experiment its fine to use "_using namespace_ ". But for larger projects usage of this is not recommended, as it may get confusing if the included headers files also have them.

Example:
```c++
// temp.cpp

#include <iostream>
using namespace std;

void something()
{
    cout << "something" << endl;
}
``` 

```c++
// main.cpp

#include "temp.cpp"

void cout()
{
    // to confuse
}

int main()
{
    std::cout << "doing something" << std::endl;  // will work fine as we explicitly mention the namepsace "std"
    cout << "will get confused now" << endl;  // compile error will get confused
    cout();  // compile error will get confused
    something();
    return 0;
}
``` 

Although you can avoid this by putting temp.cpp code into a namespace _temp_ and in main cpp create a _"using namepace "_ for it, but then the cycle may repeat for someone trying to include _main.cpp_
