### ISSUE TITLE
Arrangement issue

### ISSUE THREAD

**Issue by FahimFBA** [rutura/The-C-20-Masterclass-Source-Code#4]
The project's folder arrangement can be changed so that all of the folders come sequentially, starting from 00, 01... 
If you approve, then I can do that by adding a PR. Please let me know what do you think about that.

**Comment by Nickranjan** [comment]
What is PR  ?? @FahimFBA

**Comment by FahimFBA** [comment]
PR means Pull Request. 
The procedure is as follows:
I will clone the repo, make the changes, submit a PR. You will get the PR, check where I did change and what I changed. You will decide whether you want the change or not. If you want, then you would simply merge the PR.

**Comment by rutura** [comment]
Changing the structure would make the order confusing for udemy students where the course is broken into chapters. I assumed youtube students could find the code they need by chapter. Closing this.
