### ISSUE TITLE
naming convention for folders

### ISSUE THREAD

**Issue by devmichmich** [rutura/The-C-20-Masterclass-Source-Code#9]
When we browse the main folder **rutura/The-C-20-Masterclass-Source-Code** using web browser some subfolders are not sorted correctly. It's good to add additional '0' for folders where number of chapter is less or equal 9 
For example instead of "5.OperationsOnData" it would be probably better to have "05.OperationsOnData". Isn't it?

**Comment by Coldman22** [comment]
Yes, certainly is right.

**Comment by hansfn** [comment]
Yes, this is useful indeed. @rutura, would you like a PR for the renaming ;-) The sorting is also wrong in my terminal of course.

**Comment by hansfn** [comment]
I don't see any code changes so I assume it's not completed ;-)

**Comment by rutura** [comment]
Hello. I have them ordered as suggested. I just need to also fix the lectures that link to the git repo on udemy. Will merge the change in when it's ready.
